baseURL: https://demo.gethugothemes.com/liva/
languageCode: en-us
title: Portfolio website for Yifan Yang
theme: liva-hugo
summaryLength: '10'
paginate: 6
disqusShortname: ''
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  author: Yifan Yang
  cookies:
    enable: yes
    expire_days: 2
  copyright: '| copyright &copy; 2021 [Themefisher](https://themefisher.com/hugo-themes/)
    All Rights Reserved |'
  description: This is meta description
  email: yifany.mam2022@london.edu
  googleAnalitycsID: Your ID
  home: Home
  location: London Business School, Regent's Park, London
  logo: images/logo.png
  mobile: +44 07400989188
  
  plugins:
    css:
      - URL: plugins/bootstrap/bootstrap.min.css
      - URL: plugins/slick/slick.css
      - URL: plugins/themify-icons/themify-icons.css
      - URL: plugins/venobox/venobox.css
    js:
      - URL: plugins/jQuery/jquery.min.js
      - URL: plugins/bootstrap/bootstrap.min.js
      - URL: plugins/slick/slick.min.js
      - URL: plugins/venobox/venobox.min.js
      - URL: plugins/search/fuse.min.js
      - URL: plugins/search/mark.js
      - URL: plugins/search/search.js
  preloader:
    enable: yes
    preloader: ''
  search:
    enable: yes
  social:
    - icon: ti-facebook
      link: '#'
      title: facebook
    - icon: ti-instagram
      link: 'https://www.instagram.com/esthero1t/'
      title: instagram
    - icon: ti-github
      link: 'https://github.com/yiyesther'
      title: github
    - icon: ti-linkedin
      link: 'https://www.linkedin.com/in/yifan-yang-87b387163'
      title: linkedin
menu:
  footer:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Post
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
  main:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Post
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
